### ISSUE TITLE
more fine grade conditions states for rain.

### ISSUE THREAD

**Issue by koenraadhaedens** [iprak/weatherapi#29]
would like to have more detailed status of the rain condition. now all different codes of rain conditions like light rain or heavy rain are just displayed as rainy. A sensor the would give the state as "Light rain", Heavy rain" ... would be useful

**Comment by iprak** [comment]
Can you give me details about the state displayed in Developer Tools and the zip code ? And what card are you using?

HA only supports [these rain conditions](https://github.com/home-assistant/core/blob/6c7f2167ff0bea90a26cbb08035a8e16a2478acc/homeassistant/components/weather/__init__.py#L59) and there is nothing for light-rain. There is rain and then pouring/heavy rain. These codes would be what standard UI cards would respect.

ATTR_CONDITION_LIGHTNING = "lightning"
ATTR_CONDITION_LIGHTNING_RAINY = "lightning-rainy"
ATTR_CONDITION_PARTLYCLOUDY = "partlycloudy"
ATTR_CONDITION_POURING = "pouring"
ATTR_CONDITION_RAINY = "rainy"

The [condition codes returned by weatherapi](https://www.weatherapi.com/docs/weather_conditions.json) are more extensive and I have mapped them but weatherApi condition are overlapping so I made some judgement calls there e.g. `Moderate or heavy freezing rain` is categorized as ATTR_CONDITION_SNOWY_RAINY.

So, heavy/poring rain maps to ATTR_CONDITION_POURING and all the rest map to ATTR_CONDITION_RAINY.

I do not think a separate sensor for light/heavy rain makes sense since no card would respect that but the reported condition could be exported as an attribute. But maybe the mapping is incorrect which is why I need the data.

**Comment by iprak** [comment]
I will regardless expose the reported condition as 
![image](https://user-images.githubusercontent.com/6459774/230725742-0ec9c1b7-8c87-4c56-8571-9e07aabc0d56.png)

The condition text is locale based which is why I am opting to report the code.
